package:
  name: spdlog
  version: "1.12.0"

source:
  url: https://github.com/gabime/spdlog/archive/refs/tags/v1.12.0.tar.gz
  sha256: 4dccf2d10f410c1e2feaff89966bfc49a1abb29ef6f08246335b110e001e09a9

build:
  number: 1

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}

about:
  home: https://github.com/gabime/spdlog
  license: MIT
  license_file: LICENSE
  summary: Very fast, header-only/compiled, C++ logging library.
